### ISSUE TITLE
Invalid .json file

### ISSUE THREAD

**Issue by aichholzer** [thlorenz/turbolizer#2]
Hello @thlorenz -Great tool! I was hoping to test some code through it. However, I keep running into:
```
Invalid TurboFan JSON file
error: JSON.parse: unexpected character at line 2 column 11 of the JSON data
```

Running: `node --trace-turbo app.js` and then `turbolizer` in the same folder.
Any ideas?

**Comment by thlorenz** [comment]
Sorry this didn't work for you :(

Could you provide the Node.js version you're running so we can figure out what changed?
My hunch is that the JSON format changed a bit and I'll need to update the code from the v8 repo (to get the latest).

**Comment by aichholzer** [comment]
@thlorenz -I tried both `v8.11.3` and `v10.4.1`, same error in both cases.

**Comment by Manouchehri** [comment]
Same issue here with V8 7.0.276.40.

**Comment by Manouchehri** [comment]
Fixed locally, will push a patch later.

**Comment by aichholzer** [comment]
@Manouchehri -Would you mind sharing the fix?

**Comment by aichholzer** [comment]
Unresolved. Outdated.
